export const environment = {
  production: true,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiNGEyMGUwNS1iMjhkLTRkMjktYWM2MS02MTMxMzQyNzYzOTciLCJlbWFpbCI6InJlY2hAZ21haWwuY29tIiwiZ2l2ZW5fbmFtZSI6IkFsZXhhbmRyZSBSZWNoIiwibmJmIjoxNjk2MjYyNzY4LCJleHAiOjE2OTYyOTE1NjgsImlhdCI6MTY5NjI2Mjc2OCwiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.2allpuBwlf1AOASsA5VV6tcnhk-Qy1NEn_VGxlLObvU',
};
