export const environment = {
  production: true,
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NGU5YmQyMC0zZWQ1LTQ1MzMtYTdlZi1iMWYwOWJhNjVkMzgiLCJlbWFpbCI6InRpYWdvQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJUaWFnbyBTYW50aW5pIiwibmJmIjoxNjk2MzkwOTA5LCJleHAiOjE2OTY0MTk3MDksImlhdCI6MTY5NjM5MDkwOSwiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.dLQjAt47FsaMRPKbmD9r6JEfrNj9woQgPeVH3MJ_4ZM'
};
